name: Download Decrypted IPA

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download and Decrypt IPA
        uses: asdfzxcvbn/ipatool-action@v1.0.1
        with:
          bundle_id: "com.blutron.power"
          country: "CA"
          apple_id: "${{ secrets.APPLE_ID }}"
          apple_password: "${{ secrets.APPLE_PASSWORD }}"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blutron-decrypted-ipa
          path: "*.ipa"
