name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'action.yml'
      - '.github/workflows/build1.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download IPA
        id: download
        uses: level3tjg/decryptedappstore-action@main
        with:
          appstore_url: "https://apps.apple.com/ca/app/blutron/id1623293168"
          cache: false
          token: "${{ secrets.SESSION_TOKEN }}"

      - name: Upload Decrypted IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blutron-decrypted-ipa
          path: |
            *.ipa
            output/*.ipa
